services:
  dns-blocker:
    build: .
    container_name: dns-blocker
    restart: unless-stopped
    ports:
      - "53:53/udp"
    environment:
      - UPSTREAM_DNS=8.8.8.8
      - BLACKLIST=youtube,youtubekids,youtubei
      - WHITELIST=192.168.1.2,192.168.1.3
      - BLOCK_START_HOUR=13
      - BLOCK_START_MINUTE=0
      - BLOCK_END_HOUR=8
      - BLOCK_END_MINUTE=0
    volumes:
      - dns-logs:/app

volumes:
  dns-logs:
